version: '3.8'
services:
  redis:
    image: "redis:alpine"
  
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: tiktok-scraper
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  
  celery_worker:
    image: "python:3.8-slim"
    volumes:
      - .:/app
    working_dir: /app
    command: celery -A tiktok_scraping worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db